apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "boundary-worker.name" . }}-config
  labels:
    {{- include "boundary-worker.labels" . | nindent 4 }}
data:
  config.hcl: |

    disable_mlock = true

    listener "tcp" {
        purpose = "proxy"
        tls_disable = {{ .Values.config.tlsDisable | default "true"}}
        address = "0.0.0.0"
    }

    worker {
      name = "{{ include "boundary-worker.name" . }}"
      description = "{{ .Values.config.description | default "A worker for Boundary"}}"

      initial_upstreams = ["{{ .Values.config.controller.ip }}:80"]

      public_addr = "{{ .Values.config.hostname }}:80"
    }
    
    kms "awskms" {
      purpose    = "worker-auth"
      kms_key_id = "{{ .Values.config.kms.worker }}"
    }
